baseURL = 'https://rich-batch.github.io/auction-note/'
locale = 'ko-kr'
title = '오늘의 경매 노트'
theme = 'PaperMod'
enableRobotsTXT = true

[pagination]
pagerSize = 6

[params]
description = '경매, 공매 투자 정보 블로그'
author = 'rich-batch'
